/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ospck;

import java.awt.Toolkit;
import javax.swing.JLabel;

/**
 *
 * @author QWERTYnfinity
 */
public class Stats extends javax.swing.JFrame {
    JLabel[] atLabel = new JLabel[255];
    JLabel[] pnoLabel = new JLabel[255];
    JLabel[] btLabel = new JLabel[255];
    JLabel[] prioLabel = new JLabel[255];
    JLabel[] compLabel = new JLabel[255];
    JLabel[] turnLabel = new JLabel[255];
    JLabel[] waitLabel = new JLabel[255];
    JLabel aveTurnLabel = new JLabel();
    JLabel aveWaitLabel = new JLabel();
    JLabel statbg = new JLabel();
    int posX;
    int posY;
    /**
     * Creates new form Stats
     */
    public Stats() {
        initComponents();
        this.setLocation(100,100);
        this.setSize(600,750);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("assets/res/icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeB = new javax.swing.JLabel();
        minB = new javax.swing.JLabel();
        backB = new javax.swing.JLabel();
        handle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        closeB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ospck/assets/closeB.png"))); // NOI18N
        closeB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeBMouseExited(evt);
            }
        });
        getContentPane().add(closeB);
        closeB.setBounds(570, 2, 26, 23);

        minB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ospck/assets/minB.png"))); // NOI18N
        minB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minBMouseExited(evt);
            }
        });
        getContentPane().add(minB);
        minB.setBounds(535, 2, 26, 23);

        backB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ospck/assets/backB.png"))); // NOI18N
        backB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBMouseExited(evt);
            }
        });
        getContentPane().add(backB);
        backB.setBounds(500, 2, 26, 23);

        handle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                handleMouseDragged(evt);
            }
        });
        handle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                handleMousePressed(evt);
            }
        });
        getContentPane().add(handle);
        handle.setBounds(0, 0, 600, 13);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBMouseClicked
        this.dispose();
    }//GEN-LAST:event_backBMouseClicked

    private void backBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBMouseEntered
        // TODO add your handling code here:
        backB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ospck/assets/backB-H.png")));
    }//GEN-LAST:event_backBMouseEntered

    private void backBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBMouseExited
        // TODO add your handling code here:
        backB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ospck/assets/backB.png")));
    }//GEN-LAST:event_backBMouseExited

    private void minBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minBMouseClicked
        this.setState(Member.ICONIFIED);
    }//GEN-LAST:event_minBMouseClicked

    private void minBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minBMouseEntered
        minB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ospck/assets/minB-H.png")));
    }//GEN-LAST:event_minBMouseEntered

    private void minBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minBMouseExited
        minB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ospck/assets/minB.png")));
    }//GEN-LAST:event_minBMouseExited

    private void closeBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeBMouseClicked

    private void closeBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBMouseEntered
        closeB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ospck/assets/closeB-H.png")));
    }//GEN-LAST:event_closeBMouseEntered

    private void closeBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBMouseExited
        closeB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ospck/assets/closeB.png")));
    }//GEN-LAST:event_closeBMouseExited

    private void handleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_handleMousePressed
        posX = evt.getX();
        posY = evt.getY();
    }//GEN-LAST:event_handleMousePressed

    private void handleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_handleMouseDragged
        int movx = evt.getXOnScreen();
        int movy = evt.getYOnScreen();
        this.setLocation(movx - posX, movy - posY);
    }//GEN-LAST:event_handleMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backB;
    private javax.swing.JLabel closeB;
    private javax.swing.JLabel handle;
    private javax.swing.JLabel minB;
    // End of variables declaration//GEN-END:variables
}
